name: Trigger UiPath Orchestrator Job on Windows

on:
  push:
    branches:
      - main  # Specify the branch for triggering the workflow

jobs:
  trigger-uipath-job:
    runs-on: windows-latest

    steps:
      - name: Trigger UiPath Job
        run: |
          # Define Orchestrator details
          $orchestratorUrl = "https://cloud.uipath.com/indiuzaigqwe/DefaultTenant/orchestrator_"
          $username = "manishalakshmi.rajamani@indiumsoft.com"
          $password = "Indium@123"
          $tenantName = "DefaultTenant"
          $processKey = "03596f71-1a51-4305-abb6-85889479f363"
          $folderName = "Shared"

          # Authenticate and get access token
          $authResponse = Invoke-RestMethod -Uri "$orchestratorUrl/api/account/authenticate" `
            -Method Post `
            -ContentType "application/json" `
            -Body (@{
              usernameOrEmailAddress = $username
              password = $password
              tenant_name = $tenantName
                 } | ConvertTo-Json -Depth 10)
          $accessToken = $authResponse.result

          Write-Host "Access token retrieved successfully."

          # Start the UiPath Job
          $jobResponse = Invoke-RestMethod -Uri "$orchestratorUrl/odata/Jobs/UiPath.Server.Configuration.OData.StartJobs" `
            -Method Post `
            -Headers @{ Authorization = "Bearer $accessToken" } `
            -ContentType "application/json" `
            -Body (@{
              startInfo = @{
                ReleaseKey = $processKey
                Strategy = "ModernJobsCount"
                JobsCount = 1
                InputArguments = "{}"
                FolderName = $folderName
              }
            } | ConvertTo-Json -Depth 10)

          Write-Host "UiPath Job triggered successfully."
