name: Trigger UiPath Process (Windows)

# Trigger this workflow on push events to the main branch (or any branch you want)
on:
  push:
    branches:
      - main  # You can change this to any branch you want to track (like `develop`)

jobs:
  trigger:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 3: Trigger the UiPath Process in Orchestrator using Orchestrator API
      - name: Trigger UiPath Job in Orchestrator
        run: |
          $url = "https://cloud.uipath.com/indiuzaigqwe/DefaultTenant/orchestrator_/odata/Jobs/UiPath.Server.Configuration.OData.StartJobs"
          $headers = @{
              "Authorization" = "Bearer rt_C61246428B6EFE2693430B7320CC3950E64C2C4E8E559A81ACC0EDD615DCE27A-1"
          }
          $body = @{
              startInfo = @{
                  ReleaseKey = "03596f71-1a51-4305-abb6-85889479f363"  # Replace with the actual ReleaseKey of your process
                  Strategy = "Specific"  # Choose "Specific" or "All" based on your preference
                  RobotIds = @($1791357)  # Optional: Replace with the specific Robot ID if necessary
                  NoOfRobots = 1
                  OrganizationUnitId = $5533930
              }
          } | ConvertTo-Json

          Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $body -ContentType "application/json"

